services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: "postgres://postgres:postgres@postgres:5432/afrimart?sslmode=disable"
      SECRET_KEY: "afrimart-secret"
      RABBITMQ_URL: "amqp://admin:admin@rabbitmq:5672/"
      OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector:4317
    depends_on:
      - postgres
      - rabbitmq
      - otel-collector
  postgres:
    image: postgres:17
    container_name: afrimart-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: afrimart
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:4-management
    container_name: afrimart-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: afrimart-otel-collector
    command:
      - "--config=/etc/otelcol-contrib/config.yaml"
    volumes:
      - ./observability/otel-collector/config.yaml:/etc/otelcol-contrib/config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - tempo

  tempo:
    image: grafana/tempo:3.0.0
    container_name: afrimart-tempo
    user: "0:0"
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./observability/tempo/tempo.yaml:/etc/tempo.yaml:ro
      - tempo_data:/tmp/tempo
    ports:
      - "3200:3200"

  grafana:
    image: grafana/grafana:latest
    container_name: afrimart-grafana
    ports:
      - "3001:3000"
    depends_on:
      - tempo
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

volumes:
  postgres_data:
  rabbitmq_data:
  tempo_data:
  grafana-data: