// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    user_id,
    subtotal,
    status
)
VALUES ($1, $2, 'pending')
RETURNING id, user_id, subtotal, status, created_at, updated_at
`

type CreateOrderParams struct {
	UserID   uuid.UUID
	Subtotal string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder, arg.UserID, arg.Subtotal)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Subtotal,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    order_id,
    product_id,
    quantity,
    price
)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, product_id, quantity, price, created_at
`

type CreateOrderItemParams struct {
	OrderID   uuid.UUID
	ProductID uuid.UUID
	Quantity  int32
	Price     string
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.Price,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, subtotal, status, created_at, updated_at
FROM orders
WHERE id = $1
  AND user_id = $2
`

type GetOrderByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetOrderByID(ctx context.Context, arg GetOrderByIDParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, arg.ID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Subtotal,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT
    oi.id,
    oi.order_id,
    oi.product_id,
    oi.quantity,
    oi.price,
    oi.created_at,
    p.name AS product_name,
    p.image AS product_image
FROM order_items oi
JOIN products p ON p.id = oi.product_id
WHERE oi.order_id = $1
ORDER BY oi.created_at ASC
`

type GetOrderItemsRow struct {
	ID           uuid.UUID
	OrderID      uuid.UUID
	ProductID    uuid.UUID
	Quantity     int32
	Price        string
	CreatedAt    time.Time
	ProductName  string
	ProductImage sql.NullString
}

func (q *Queries) GetOrderItems(ctx context.Context, orderID uuid.UUID) ([]GetOrderItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsRow
	for rows.Next() {
		var i GetOrderItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.Price,
			&i.CreatedAt,
			&i.ProductName,
			&i.ProductImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, user_id, subtotal, status, created_at, updated_at
FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListOrdersByUserParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Subtotal,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reduceProductStock = `-- name: ReduceProductStock :one
UPDATE products
SET
    stock = stock - $2,
    updated_at = NOW()
WHERE id = $1
  AND stock >= $2
RETURNING id, stock
`

type ReduceProductStockParams struct {
	ID    uuid.UUID
	Stock int32
}

type ReduceProductStockRow struct {
	ID    uuid.UUID
	Stock int32
}

func (q *Queries) ReduceProductStock(ctx context.Context, arg ReduceProductStockParams) (ReduceProductStockRow, error) {
	row := q.db.QueryRowContext(ctx, reduceProductStock, arg.ID, arg.Stock)
	var i ReduceProductStockRow
	err := row.Scan(&i.ID, &i.Stock)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET
    status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, subtotal, status, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Subtotal,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyOrderSellerOwnership = `-- name: VerifyOrderSellerOwnership :one
SELECT o.status
FROM orders o
JOIN order_items oi ON oi.order_id = o.id
JOIN products p ON p.id = oi.product_id
JOIN shops s ON s.id = p.shop_id
WHERE o.id = $1
  AND s.owner_id = $2
LIMIT 1
`

type VerifyOrderSellerOwnershipParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) VerifyOrderSellerOwnership(ctx context.Context, arg VerifyOrderSellerOwnershipParams) (string, error) {
	row := q.db.QueryRowContext(ctx, verifyOrderSellerOwnership, arg.ID, arg.OwnerID)
	var status string
	err := row.Scan(&status)
	return status, err
}
