// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    order_id,
    payment_method,
    payment_status,
    amount,
    provider,
    transaction_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
) RETURNING id, order_id, payment_method, payment_status, amount, provider, transaction_id, provider_reference, failure_reason, paid_at, created_at, updated_at
`

type CreatePaymentParams struct {
	OrderID       uuid.UUID
	PaymentMethod string
	PaymentStatus string
	Amount        string
	Provider      sql.NullString
	TransactionID sql.NullString
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.OrderID,
		arg.PaymentMethod,
		arg.PaymentStatus,
		arg.Amount,
		arg.Provider,
		arg.TransactionID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.Amount,
		&i.Provider,
		&i.TransactionID,
		&i.ProviderReference,
		&i.FailureReason,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpiredPendingPayments = `-- name: GetExpiredPendingPayments :many
SELECT id, order_id 
FROM payments 
WHERE payment_method = 'online' 
  AND payment_status = 'pending' 
  AND created_at < $1
`

type GetExpiredPendingPaymentsRow struct {
	ID      uuid.UUID
	OrderID uuid.UUID
}

func (q *Queries) GetExpiredPendingPayments(ctx context.Context, createdAt time.Time) ([]GetExpiredPendingPaymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getExpiredPendingPayments, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpiredPendingPaymentsRow
	for rows.Next() {
		var i GetExpiredPendingPaymentsRow
		if err := rows.Scan(&i.ID, &i.OrderID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentByOrderID = `-- name: GetPaymentByOrderID :one
SELECT id, order_id, payment_method, payment_status, amount, provider, transaction_id, provider_reference, failure_reason, paid_at, created_at, updated_at FROM payments
WHERE order_id = $1
LIMIT 1
`

func (q *Queries) GetPaymentByOrderID(ctx context.Context, orderID uuid.UUID) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByOrderID, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.Amount,
		&i.Provider,
		&i.TransactionID,
		&i.ProviderReference,
		&i.FailureReason,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByProviderRef = `-- name: GetPaymentByProviderRef :one
SELECT id, order_id, payment_method, payment_status, amount, provider, transaction_id, provider_reference, failure_reason, paid_at, created_at, updated_at FROM payments 
WHERE provider_reference = $1 
LIMIT 1
`

func (q *Queries) GetPaymentByProviderRef(ctx context.Context, providerReference sql.NullString) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByProviderRef, providerReference)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.Amount,
		&i.Provider,
		&i.TransactionID,
		&i.ProviderReference,
		&i.FailureReason,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentStatusConditional = `-- name: UpdatePaymentStatusConditional :execrows
UPDATE payments
SET
    payment_status = $1,
    paid_at = COALESCE($2, paid_at),
    provider_reference = COALESCE($3, provider_reference),
    transaction_id = COALESCE($4, transaction_id),
    failure_reason = COALESCE($5, failure_reason),
    updated_at = NOW()
WHERE id = $6 AND payment_status = $7
`

type UpdatePaymentStatusConditionalParams struct {
	NewStatus         string
	PaidAt            sql.NullTime
	ProviderReference sql.NullString
	TransactionID     sql.NullString
	FailureReason     sql.NullString
	ID                uuid.UUID
	CurrentStatus     string
}

func (q *Queries) UpdatePaymentStatusConditional(ctx context.Context, arg UpdatePaymentStatusConditionalParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePaymentStatusConditional,
		arg.NewStatus,
		arg.PaidAt,
		arg.ProviderReference,
		arg.TransactionID,
		arg.FailureReason,
		arg.ID,
		arg.CurrentStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
