// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_images.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createProductImage = `-- name: CreateProductImage :one
INSERT INTO product_images (
    product_id,
    object_key,
    display_order
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, product_id, object_key, display_order, created_at
`

type CreateProductImageParams struct {
	ProductID    uuid.UUID
	ObjectKey    string
	DisplayOrder int32
}

func (q *Queries) CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error) {
	row := q.db.QueryRowContext(ctx, createProductImage, arg.ProductID, arg.ObjectKey, arg.DisplayOrder)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ObjectKey,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProductImage = `-- name: DeleteProductImage :one
DELETE FROM product_images
WHERE id = $1
  AND product_id = $2
RETURNING id, product_id, object_key, display_order, created_at
`

type DeleteProductImageParams struct {
	ID        uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) DeleteProductImage(ctx context.Context, arg DeleteProductImageParams) (ProductImage, error) {
	row := q.db.QueryRowContext(ctx, deleteProductImage, arg.ID, arg.ProductID)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ObjectKey,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getProductImage = `-- name: GetProductImage :one
SELECT id, product_id, object_key, display_order, created_at
FROM product_images
WHERE id = $1
  AND product_id = $2
`

type GetProductImageParams struct {
	ID        uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) GetProductImage(ctx context.Context, arg GetProductImageParams) (ProductImage, error) {
	row := q.db.QueryRowContext(ctx, getProductImage, arg.ID, arg.ProductID)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ObjectKey,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getProductImages = `-- name: GetProductImages :many
SELECT id, product_id, object_key, display_order, created_at
FROM product_images
WHERE product_id = $1
ORDER BY display_order ASC, created_at ASC
`

func (q *Queries) GetProductImages(ctx context.Context, productID uuid.UUID) ([]ProductImage, error) {
	rows, err := q.db.QueryContext(ctx, getProductImages, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductImage
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ObjectKey,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductImage = `-- name: UpdateProductImage :one
UPDATE product_images
SET
    object_key = $3
WHERE id = $1
  AND product_id = $2
RETURNING id, product_id, object_key, display_order, created_at
`

type UpdateProductImageParams struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	ObjectKey string
}

func (q *Queries) UpdateProductImage(ctx context.Context, arg UpdateProductImageParams) (ProductImage, error) {
	row := q.db.QueryRowContext(ctx, updateProductImage, arg.ID, arg.ProductID, arg.ObjectKey)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ObjectKey,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}
