// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one

INSERT INTO products (
    shop_id,
    category_id,
    subcategory_id,
    name,
    description,
    brand,
    color,
    size,
    price,
    stock,
    status
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING id, shop_id, category_id, subcategory_id, name, description, brand, color, size, price, stock, status, created_at, updated_at, gender
`

type CreateProductParams struct {
	ShopID        uuid.UUID
	CategoryID    uuid.UUID
	SubcategoryID uuid.UUID
	Name          string
	Description   sql.NullString
	Brand         sql.NullString
	Color         sql.NullString
	Size          sql.NullString
	Price         string
	Stock         int32
	Status        string
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.ShopID,
		arg.CategoryID,
		arg.SubcategoryID,
		arg.Name,
		arg.Description,
		arg.Brand,
		arg.Color,
		arg.Size,
		arg.Price,
		arg.Stock,
		arg.Status,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.Name,
		&i.Description,
		&i.Brand,
		&i.Color,
		&i.Size,
		&i.Price,
		&i.Stock,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Gender,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec

DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getCategory = `-- name: GetCategory :one

SELECT id, name, created_at
FROM categories
WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getProduct = `-- name: GetProduct :one

SELECT id, shop_id, category_id, subcategory_id, name, description, brand, color, size, price, stock, status, created_at, updated_at, gender
FROM products
WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.Name,
		&i.Description,
		&i.Brand,
		&i.Color,
		&i.Size,
		&i.Price,
		&i.Stock,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Gender,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many

SELECT id, name, created_at
FROM categories
ORDER BY name ASC
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many

SELECT id, shop_id, category_id, subcategory_id, name, description, brand, color, size, price, stock, status, created_at, updated_at, gender
FROM products
WHERE status = 'active'
  AND (
      $1::text = ''
      OR name ILIKE '%' || $1::text || '%'
      OR brand ILIKE '%' || $1::text || '%'
      OR description ILIKE '%' || $1::text || '%'
  )
  AND (
      $2::uuid IS NULL
      OR category_id = $2::uuid
  )
  AND (
      $3::uuid IS NULL
      OR subcategory_id = $3::uuid
  )
  AND (
      $4::text = ''
      OR brand ILIKE '%' || $4::text || '%'
  )
  AND (
      $5::text = ''
      OR color ILIKE '%' || $5::text || '%'
  )
  AND (
      $6::text = ''
      OR size = $6::text
  )
  AND (
      $7::numeric IS NULL
      OR price >= $7::numeric
  )
  AND (
      $8::numeric IS NULL
      OR price <= $8::numeric
  )
ORDER BY created_at DESC
LIMIT $10
OFFSET $9
`

type ListProductsParams struct {
	Search        string
	CategoryID    uuid.NullUUID
	SubcategoryID uuid.NullUUID
	Brand         string
	Color         string
	Size          string
	MinPrice      sql.NullString
	MaxPrice      sql.NullString
	PageOffset    int32
	PageLimit     int32
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts,
		arg.Search,
		arg.CategoryID,
		arg.SubcategoryID,
		arg.Brand,
		arg.Color,
		arg.Size,
		arg.MinPrice,
		arg.MaxPrice,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.CategoryID,
			&i.SubcategoryID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Color,
			&i.Size,
			&i.Price,
			&i.Stock,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Gender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategory = `-- name: ListProductsByCategory :many

SELECT id, shop_id, category_id, subcategory_id, name, description, brand, color, size, price, stock, status, created_at, updated_at, gender
FROM products
WHERE category_id = $1
  AND status = 'active'
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListProductsByCategoryParams struct {
	CategoryID uuid.UUID
	Limit      int32
	Offset     int32
}

func (q *Queries) ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.CategoryID,
			&i.SubcategoryID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Color,
			&i.Size,
			&i.Price,
			&i.Stock,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Gender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByShop = `-- name: ListProductsByShop :many

SELECT id, shop_id, category_id, subcategory_id, name, description, brand, color, size, price, stock, status, created_at, updated_at, gender
FROM products
WHERE shop_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListProductsByShopParams struct {
	ShopID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListProductsByShop(ctx context.Context, arg ListProductsByShopParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByShop, arg.ShopID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.CategoryID,
			&i.SubcategoryID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Color,
			&i.Size,
			&i.Price,
			&i.Stock,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Gender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsBySubcategory = `-- name: ListProductsBySubcategory :many

SELECT id, shop_id, category_id, subcategory_id, name, description, brand, color, size, price, stock, status, created_at, updated_at, gender
FROM products
WHERE subcategory_id = $1
  AND status = 'active'
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListProductsBySubcategoryParams struct {
	SubcategoryID uuid.UUID
	Limit         int32
	Offset        int32
}

func (q *Queries) ListProductsBySubcategory(ctx context.Context, arg ListProductsBySubcategoryParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsBySubcategory, arg.SubcategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.CategoryID,
			&i.SubcategoryID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Color,
			&i.Size,
			&i.Price,
			&i.Stock,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Gender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubcategoriesByCategory = `-- name: ListSubcategoriesByCategory :many

SELECT id, category_id, name, created_at
FROM subcategories
WHERE category_id = $1
ORDER BY name ASC
`

func (q *Queries) ListSubcategoriesByCategory(ctx context.Context, categoryID uuid.UUID) ([]Subcategory, error) {
	rows, err := q.db.QueryContext(ctx, listSubcategoriesByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subcategory
	for rows.Next() {
		var i Subcategory
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one

UPDATE products
SET
    category_id = $2,
    subcategory_id = $3,
    name = $4,
    description = $5,
    brand = $6,
    color = $7,
    size = $8,
    price = $9,
    stock = $10,
    status = $11,
    updated_at = NOW()
WHERE id = $1
RETURNING id, shop_id, category_id, subcategory_id, name, description, brand, color, size, price, stock, status, created_at, updated_at, gender
`

type UpdateProductParams struct {
	ID            uuid.UUID
	CategoryID    uuid.UUID
	SubcategoryID uuid.UUID
	Name          string
	Description   sql.NullString
	Brand         sql.NullString
	Color         sql.NullString
	Size          sql.NullString
	Price         string
	Stock         int32
	Status        string
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.ID,
		arg.CategoryID,
		arg.SubcategoryID,
		arg.Name,
		arg.Description,
		arg.Brand,
		arg.Color,
		arg.Size,
		arg.Price,
		arg.Stock,
		arg.Status,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.Name,
		&i.Description,
		&i.Brand,
		&i.Color,
		&i.Size,
		&i.Price,
		&i.Stock,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Gender,
	)
	return i, err
}
