// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one

INSERT INTO products (
    shop_id,
    category_id,
    subcategory_id,
    name,
    description,
    brand,
    color,
    size,
    gender,
    price,
    status,
    stock
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
RETURNING id, shop_id, category_id, subcategory_id, name, description, brand, color, size, price, stock, status, created_at, updated_at, gender
`

type CreateProductParams struct {
	ShopID        uuid.UUID
	CategoryID    uuid.UUID
	SubcategoryID uuid.UUID
	Name          string
	Description   sql.NullString
	Brand         sql.NullString
	Color         sql.NullString
	Size          sql.NullString
	Gender        string
	Price         string
	Status        string
	Stock         int32
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.ShopID,
		arg.CategoryID,
		arg.SubcategoryID,
		arg.Name,
		arg.Description,
		arg.Brand,
		arg.Color,
		arg.Size,
		arg.Gender,
		arg.Price,
		arg.Status,
		arg.Stock,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.Name,
		&i.Description,
		&i.Brand,
		&i.Color,
		&i.Size,
		&i.Price,
		&i.Stock,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Gender,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec

DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getCategory = `-- name: GetCategory :one

SELECT id, name, created_at
FROM categories
WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT
    p.id, p.shop_id, p.category_id, p.subcategory_id, p.name, p.description, p.brand, p.color, p.size, p.price, p.stock, p.status, p.created_at, p.updated_at, p.gender,
    s.name AS shop_name
FROM products p
JOIN shops s ON s.id = p.shop_id
WHERE p.id = $1
`

type GetProductRow struct {
	ID            uuid.UUID
	ShopID        uuid.UUID
	CategoryID    uuid.UUID
	SubcategoryID uuid.UUID
	Name          string
	Description   sql.NullString
	Brand         sql.NullString
	Color         sql.NullString
	Size          sql.NullString
	Price         string
	Stock         int32
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Gender        string
	ShopName      string
}

func (q *Queries) GetProduct(ctx context.Context, id uuid.UUID) (GetProductRow, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i GetProductRow
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.Name,
		&i.Description,
		&i.Brand,
		&i.Color,
		&i.Size,
		&i.Price,
		&i.Stock,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Gender,
		&i.ShopName,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many

SELECT id, name, created_at
FROM categories
ORDER BY name ASC
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many

SELECT
    p.id, p.shop_id, p.category_id, p.subcategory_id, p.name, p.description, p.brand, p.color, p.size, p.price, p.stock, p.status, p.created_at, p.updated_at, p.gender,
    s.name AS shop_name
FROM products p
JOIN shops s ON s.id = p.shop_id
WHERE p.status = 'active'
  AND s.status = 'active'
  AND (
      $1::text = ''
      OR p.name ILIKE '%' || $1::text || '%'
      OR p.brand ILIKE '%' || $1::text || '%'
      OR p.description ILIKE '%' || $1::text || '%'
  )
  AND (
      $2::uuid IS NULL
      OR p.category_id = $2::uuid
  )
  AND (
      $3::uuid IS NULL
      OR p.subcategory_id = $3::uuid
  )
  AND (
      $4::text = ''
      OR p.brand ILIKE '%' || $4::text || '%'
  )
  AND (
      $5::text = ''
      OR p.color ILIKE '%' || $5::text || '%'
  )
  AND (
      $6::text = ''
      OR p.size = $6::text
  )
  AND (
      $7::numeric IS NULL
      OR p.price >= $7::numeric
  )
  AND (
      $8::numeric IS NULL
      OR p.price <= $8::numeric
  )
ORDER BY p.created_at DESC
LIMIT $10
OFFSET $9
`

type ListProductsParams struct {
	Search        string
	CategoryID    uuid.NullUUID
	SubcategoryID uuid.NullUUID
	Brand         string
	Color         string
	Size          string
	MinPrice      sql.NullString
	MaxPrice      sql.NullString
	PageOffset    int32
	PageLimit     int32
}

type ListProductsRow struct {
	ID            uuid.UUID
	ShopID        uuid.UUID
	CategoryID    uuid.UUID
	SubcategoryID uuid.UUID
	Name          string
	Description   sql.NullString
	Brand         sql.NullString
	Color         sql.NullString
	Size          sql.NullString
	Price         string
	Stock         int32
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Gender        string
	ShopName      string
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProducts,
		arg.Search,
		arg.CategoryID,
		arg.SubcategoryID,
		arg.Brand,
		arg.Color,
		arg.Size,
		arg.MinPrice,
		arg.MaxPrice,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.CategoryID,
			&i.SubcategoryID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Color,
			&i.Size,
			&i.Price,
			&i.Stock,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Gender,
			&i.ShopName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategory = `-- name: ListProductsByCategory :many

SELECT
    p.id, p.shop_id, p.category_id, p.subcategory_id, p.name, p.description, p.brand, p.color, p.size, p.price, p.stock, p.status, p.created_at, p.updated_at, p.gender,
    s.name AS shop_name
FROM products p
JOIN shops s ON s.id = p.shop_id
WHERE p.category_id = $1
  AND p.status = 'active'
  AND s.status = 'active'
ORDER BY p.created_at DESC
LIMIT $2
OFFSET $3
`

type ListProductsByCategoryParams struct {
	CategoryID uuid.UUID
	Limit      int32
	Offset     int32
}

type ListProductsByCategoryRow struct {
	ID            uuid.UUID
	ShopID        uuid.UUID
	CategoryID    uuid.UUID
	SubcategoryID uuid.UUID
	Name          string
	Description   sql.NullString
	Brand         sql.NullString
	Color         sql.NullString
	Size          sql.NullString
	Price         string
	Stock         int32
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Gender        string
	ShopName      string
}

func (q *Queries) ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]ListProductsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsByCategoryRow
	for rows.Next() {
		var i ListProductsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.CategoryID,
			&i.SubcategoryID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Color,
			&i.Size,
			&i.Price,
			&i.Stock,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Gender,
			&i.ShopName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByShop = `-- name: ListProductsByShop :many

SELECT
    p.id, p.shop_id, p.category_id, p.subcategory_id, p.name, p.description, p.brand, p.color, p.size, p.price, p.stock, p.status, p.created_at, p.updated_at, p.gender,
    s.name AS shop_name
FROM products p
JOIN shops s ON s.id = p.shop_id
WHERE p.shop_id = $1
  AND p.status = 'active'
  AND s.status = 'active'
ORDER BY p.created_at DESC
LIMIT $2
OFFSET $3
`

type ListProductsByShopParams struct {
	ShopID uuid.UUID
	Limit  int32
	Offset int32
}

type ListProductsByShopRow struct {
	ID            uuid.UUID
	ShopID        uuid.UUID
	CategoryID    uuid.UUID
	SubcategoryID uuid.UUID
	Name          string
	Description   sql.NullString
	Brand         sql.NullString
	Color         sql.NullString
	Size          sql.NullString
	Price         string
	Stock         int32
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Gender        string
	ShopName      string
}

func (q *Queries) ListProductsByShop(ctx context.Context, arg ListProductsByShopParams) ([]ListProductsByShopRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByShop, arg.ShopID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsByShopRow
	for rows.Next() {
		var i ListProductsByShopRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.CategoryID,
			&i.SubcategoryID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Color,
			&i.Size,
			&i.Price,
			&i.Stock,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Gender,
			&i.ShopName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsBySubcategory = `-- name: ListProductsBySubcategory :many

SELECT
    p.id, p.shop_id, p.category_id, p.subcategory_id, p.name, p.description, p.brand, p.color, p.size, p.price, p.stock, p.status, p.created_at, p.updated_at, p.gender,
    s.name AS shop_name
FROM products p
JOIN shops s ON s.id = p.shop_id
WHERE p.subcategory_id = $1
  AND p.status = 'active'
  AND s.status = 'active'
ORDER BY p.created_at DESC
LIMIT $2
OFFSET $3
`

type ListProductsBySubcategoryParams struct {
	SubcategoryID uuid.UUID
	Limit         int32
	Offset        int32
}

type ListProductsBySubcategoryRow struct {
	ID            uuid.UUID
	ShopID        uuid.UUID
	CategoryID    uuid.UUID
	SubcategoryID uuid.UUID
	Name          string
	Description   sql.NullString
	Brand         sql.NullString
	Color         sql.NullString
	Size          sql.NullString
	Price         string
	Stock         int32
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Gender        string
	ShopName      string
}

func (q *Queries) ListProductsBySubcategory(ctx context.Context, arg ListProductsBySubcategoryParams) ([]ListProductsBySubcategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductsBySubcategory, arg.SubcategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsBySubcategoryRow
	for rows.Next() {
		var i ListProductsBySubcategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.CategoryID,
			&i.SubcategoryID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Color,
			&i.Size,
			&i.Price,
			&i.Stock,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Gender,
			&i.ShopName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubcategoriesByCategory = `-- name: ListSubcategoriesByCategory :many

SELECT id, category_id, name, created_at
FROM subcategories
WHERE category_id = $1
ORDER BY name ASC
`

func (q *Queries) ListSubcategoriesByCategory(ctx context.Context, categoryID uuid.UUID) ([]Subcategory, error) {
	rows, err := q.db.QueryContext(ctx, listSubcategoriesByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subcategory
	for rows.Next() {
		var i Subcategory
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one

UPDATE products
SET
    category_id = $2,
    subcategory_id = $3,
    name = $4,
    description = $5,
    brand = $6,
    color = $7,
    size = $8,
    price = $9,
    stock = $10,
    status = $11,
    updated_at = NOW()
WHERE id = $1
RETURNING id, shop_id, category_id, subcategory_id, name, description, brand, color, size, price, stock, status, created_at, updated_at, gender
`

type UpdateProductParams struct {
	ID            uuid.UUID
	CategoryID    uuid.UUID
	SubcategoryID uuid.UUID
	Name          string
	Description   sql.NullString
	Brand         sql.NullString
	Color         sql.NullString
	Size          sql.NullString
	Price         string
	Stock         int32
	Status        string
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.ID,
		arg.CategoryID,
		arg.SubcategoryID,
		arg.Name,
		arg.Description,
		arg.Brand,
		arg.Color,
		arg.Size,
		arg.Price,
		arg.Stock,
		arg.Status,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.Name,
		&i.Description,
		&i.Brand,
		&i.Color,
		&i.Size,
		&i.Price,
		&i.Stock,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Gender,
	)
	return i, err
}
