// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one

INSERT INTO products (
    shop_id,
    category_id,
    subcategory_id,
    name,
    description,
    brand,
    color,
    size,
    price,
    stock,
    image,
    status
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
RETURNING id, shop_id, category_id, subcategory_id, name, description, brand, color, size, price, stock, image, status, created_at, updated_at
`

type CreateProductParams struct {
	ShopID        uuid.UUID
	CategoryID    uuid.UUID
	SubcategoryID uuid.UUID
	Name          string
	Description   sql.NullString
	Brand         sql.NullString
	Color         sql.NullString
	Size          sql.NullString
	Price         string
	Stock         int32
	Image         sql.NullString
	Status        string
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.ShopID,
		arg.CategoryID,
		arg.SubcategoryID,
		arg.Name,
		arg.Description,
		arg.Brand,
		arg.Color,
		arg.Size,
		arg.Price,
		arg.Stock,
		arg.Image,
		arg.Status,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.Name,
		&i.Description,
		&i.Brand,
		&i.Color,
		&i.Size,
		&i.Price,
		&i.Stock,
		&i.Image,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec

DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one

SELECT id, shop_id, category_id, subcategory_id, name, description, brand, color, size, price, stock, image, status, created_at, updated_at
FROM products
WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.Name,
		&i.Description,
		&i.Brand,
		&i.Color,
		&i.Size,
		&i.Price,
		&i.Stock,
		&i.Image,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many

SELECT id, shop_id, category_id, subcategory_id, name, description, brand, color, size, price, stock, image, status, created_at, updated_at
FROM products
WHERE status = 'active'
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type ListProductsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.CategoryID,
			&i.SubcategoryID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Color,
			&i.Size,
			&i.Price,
			&i.Stock,
			&i.Image,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategory = `-- name: ListProductsByCategory :many

SELECT id, shop_id, category_id, subcategory_id, name, description, brand, color, size, price, stock, image, status, created_at, updated_at
FROM products
WHERE category_id = $1
  AND status = 'active'
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListProductsByCategoryParams struct {
	CategoryID uuid.UUID
	Limit      int32
	Offset     int32
}

func (q *Queries) ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.CategoryID,
			&i.SubcategoryID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Color,
			&i.Size,
			&i.Price,
			&i.Stock,
			&i.Image,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByShop = `-- name: ListProductsByShop :many

SELECT id, shop_id, category_id, subcategory_id, name, description, brand, color, size, price, stock, image, status, created_at, updated_at
FROM products
WHERE shop_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListProductsByShopParams struct {
	ShopID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListProductsByShop(ctx context.Context, arg ListProductsByShopParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByShop, arg.ShopID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.CategoryID,
			&i.SubcategoryID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Color,
			&i.Size,
			&i.Price,
			&i.Stock,
			&i.Image,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsBySubcategory = `-- name: ListProductsBySubcategory :many

SELECT id, shop_id, category_id, subcategory_id, name, description, brand, color, size, price, stock, image, status, created_at, updated_at
FROM products
WHERE subcategory_id = $1
  AND status = 'active'
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListProductsBySubcategoryParams struct {
	SubcategoryID uuid.UUID
	Limit         int32
	Offset        int32
}

func (q *Queries) ListProductsBySubcategory(ctx context.Context, arg ListProductsBySubcategoryParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsBySubcategory, arg.SubcategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.CategoryID,
			&i.SubcategoryID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Color,
			&i.Size,
			&i.Price,
			&i.Stock,
			&i.Image,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one

UPDATE products
SET
    category_id = $2,
    subcategory_id = $3,
    name = $4,
    description = $5,
    brand = $6,
    color = $7,
    size = $8,
    price = $9,
    stock = $10,
    image = $11,
    status = $12,
    updated_at = NOW()
WHERE id = $1
RETURNING id, shop_id, category_id, subcategory_id, name, description, brand, color, size, price, stock, image, status, created_at, updated_at
`

type UpdateProductParams struct {
	ID            uuid.UUID
	CategoryID    uuid.UUID
	SubcategoryID uuid.UUID
	Name          string
	Description   sql.NullString
	Brand         sql.NullString
	Color         sql.NullString
	Size          sql.NullString
	Price         string
	Stock         int32
	Image         sql.NullString
	Status        string
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.ID,
		arg.CategoryID,
		arg.SubcategoryID,
		arg.Name,
		arg.Description,
		arg.Brand,
		arg.Color,
		arg.Size,
		arg.Price,
		arg.Stock,
		arg.Image,
		arg.Status,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.Name,
		&i.Description,
		&i.Brand,
		&i.Color,
		&i.Size,
		&i.Price,
		&i.Stock,
		&i.Image,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
