// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refToken.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (token_hash, created_at, user_id, expires_at, revoked_at)
VALUES (
    $1,
    Now(),
    $2,
    Now() + INTERVAL '30 days',
    NULL
)
RETURNING id, user_id, token_hash, expires_at, revoked_at, created_at
`

type CreateRefreshTokenParams struct {
	TokenHash string
	UserID    uuid.UUID
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.TokenHash, arg.UserID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_hash, expires_at, revoked_at, created_at FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :one
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE token_hash = $1
  AND revoked_at IS NULL
RETURNING id
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, revokeRefreshToken, tokenHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
