// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shop.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const activateShop = `-- name: ActivateShop :one
UPDATE shops
SET
    status = 'active',
    updated_at = NOW()
WHERE id = $1
AND owner_id = $2
RETURNING id, owner_id, name, description, status, created_at, updated_at
`

type ActivateShopParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) ActivateShop(ctx context.Context, arg ActivateShopParams) (Shop, error) {
	row := q.db.QueryRowContext(ctx, activateShop, arg.ID, arg.OwnerID)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createShop = `-- name: CreateShop :one
INSERT INTO shops (
    id,
    owner_id,
    name,
    description
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, owner_id, name, description, status, created_at, updated_at
`

type CreateShopParams struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	Name        string
	Description sql.NullString
}

func (q *Queries) CreateShop(ctx context.Context, arg CreateShopParams) (Shop, error) {
	row := q.db.QueryRowContext(ctx, createShop,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Description,
	)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateShop = `-- name: DeactivateShop :one
UPDATE shops
SET
    status = 'inactive',
    updated_at = NOW()
WHERE id = $1
AND owner_id = $2
RETURNING id, owner_id, name, description, status, created_at, updated_at
`

type DeactivateShopParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) DeactivateShop(ctx context.Context, arg DeactivateShopParams) (Shop, error) {
	row := q.db.QueryRowContext(ctx, deactivateShop, arg.ID, arg.OwnerID)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShopByID = `-- name: GetShopByID :one
SELECT id, owner_id, name, description, status, created_at, updated_at
FROM shops
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetShopByID(ctx context.Context, id uuid.UUID) (Shop, error) {
	row := q.db.QueryRowContext(ctx, getShopByID, id)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShopByIDAndOwnerID = `-- name: GetShopByIDAndOwnerID :one

SELECT id, owner_id, name, description, status, created_at, updated_at
FROM shops
WHERE id = $1
  AND owner_id = $2
`

type GetShopByIDAndOwnerIDParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) GetShopByIDAndOwnerID(ctx context.Context, arg GetShopByIDAndOwnerIDParams) (Shop, error) {
	row := q.db.QueryRowContext(ctx, getShopByIDAndOwnerID, arg.ID, arg.OwnerID)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShopByOwnerID = `-- name: GetShopByOwnerID :one
SELECT id, owner_id, name, description, status, created_at, updated_at
FROM shops
WHERE owner_id = $1
LIMIT 1
`

func (q *Queries) GetShopByOwnerID(ctx context.Context, ownerID uuid.UUID) (Shop, error) {
	row := q.db.QueryRowContext(ctx, getShopByOwnerID, ownerID)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateShopDescription = `-- name: UpdateShopDescription :one
UPDATE shops
SET
    description = $2,
    updated_at = NOW()
WHERE id = $1
AND owner_id = $3
RETURNING id, owner_id, name, description, status, created_at, updated_at
`

type UpdateShopDescriptionParams struct {
	ID          uuid.UUID
	Description sql.NullString
	OwnerID     uuid.UUID
}

func (q *Queries) UpdateShopDescription(ctx context.Context, arg UpdateShopDescriptionParams) (Shop, error) {
	row := q.db.QueryRowContext(ctx, updateShopDescription, arg.ID, arg.Description, arg.OwnerID)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateShopName = `-- name: UpdateShopName :one
UPDATE shops
SET
    name = $2,
    updated_at = NOW()
WHERE id = $1
AND owner_id = $3
RETURNING id, owner_id, name, description, status, created_at, updated_at
`

type UpdateShopNameParams struct {
	ID      uuid.UUID
	Name    string
	OwnerID uuid.UUID
}

func (q *Queries) UpdateShopName(ctx context.Context, arg UpdateShopNameParams) (Shop, error) {
	row := q.db.QueryRowContext(ctx, updateShopName, arg.ID, arg.Name, arg.OwnerID)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
